/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  SideMenu as SideMenu
} from './components/side-menu/side-menu';

declare global {
  interface HTMLSideMenuElement extends SideMenu, HTMLStencilElement {
  }
  var HTMLSideMenuElement: {
    prototype: HTMLSideMenuElement;
    new (): HTMLSideMenuElement;
  };
  interface HTMLElementTagNameMap {
    "side-menu": HTMLSideMenuElement;
  }
  interface ElementTagNameMap {
    "side-menu": HTMLSideMenuElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "side-menu": JSXElements.SideMenuAttributes;
    }
  }
  namespace JSXElements {
    export interface SideMenuAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
